name: 'Joe Urbz Media & Photography'
favicon: null
layout_spectrum: 0.90322
typography_spectrum: 0.79517
title: 'Joe Urbz Media & Photography'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#060503'
    - '#fffcf9'
    - '#fed0a3'
    - '#6e5b56'
    - '#e0a06c'
  brandStrength: 0.5
  lightness: 0.4375
  saturation: 0.375
  rhythmicContrast: 0.75
purpose: []
