name: 'Joe Urbz Media & Photography'
favicon: null
layout_spectrum: 0.42583
typography_spectrum: 0.70492
title: 'Joe Urbz Media & Photography'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#152f3f'
    - '#29536d'
    - '#fc903d'
    - '#a74851'
  brandStrength: 0.5
  lightness: 0.5625
  saturation: 0.6875
  rhythmicContrast: 0.75
purpose: []
