name: 'Joe Urbz Media & Photography'
favicon: null
layout_spectrum: 0.5081575461663306
typography_spectrum: 0.386330334469676
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#686868'
    - '#d6d4d5'
    - '#282828'
    - '#4b4b4b'
  brandStrength: 0.5
  lightness: 0.5798530327156186
  saturation: 0.22203273116610944
  rhythmicContrast: 0.1425721882842481
purpose: []
