name: 'Joe Urbz Media & Photography'
favicon: null
layout_spectrum: 0
typography_spectrum: 0.1681
title: 'Joe Urbz Media & Photography'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#152f3f'
    - '#29536d'
    - '#fc903d'
    - '#a74851'
  brandStrength: 0
  lightness: 0.625
  saturation: 0.625
  rhythmicContrast: 0.5
purpose: []
